Start new registration and program information display flow
mitesp/espider pull request #61
Opened 2020-07-27 16:51 UTC by wishdasher

New stuff at `beta/:program/:edition`. Copied over necessary parts from certain files in `client/src/registration`.

Mostly restructured how the components worked with each other, separated out teacher and student program pages.

Next:
- actually enforce a registration steps -> program page info flow
- add in general program information to the relevant pages
- protect certain URLs and redirect logged in / not logged in traffic accordingly
- delete old files from `registration`

2020-07-28 23:55 UTC, mvadari requested changes

2020-07-28 23:55 UTC, mvadari commented on client/src/program/ProgramPage.tsx
> +        <StudentProgramPage program={program} edition={edition} />
What's going on here? Why is the `StudentProgramPage` being displayed if the user is neither a student nor a teacher? If this is a placeholder, can you add a `TODO`?

2020-07-28 23:55 UTC, mvadari commented on client/src/program/GeneralStudentPage.tsx
> +      props.checks.availabilityCheck;
Should this be replaced with `isRegistered` or will that include things like payment checks?

2020-07-28 23:55 UTC, mvadari commented on client/src/program/StudentProgramPage.tsx
> +        <GeneralStudentPage
This naming scheme is confusing. Until I saw this line, I was confused about what the difference was between `StudentProgramPage` and `GeneralStudentPage`.

2020-07-28 23:55 UTC, mvadari commented on client/src/program/helpers.ts
> +export { isStudentRegistered };
If this isn't being used right now, I would take it out and put it back in when it is being used.

2020-07-31 19:58 UTC, wishdasher commented on client/src/program/ProgramPage.tsx
> +        <StudentProgramPage program={program} edition={edition} />
We talked about student view potentially being a default, but `TODO` for now.

2020-07-31 20:00 UTC, wishdasher commented on client/src/program/GeneralStudentPage.tsx
> +      props.checks.availabilityCheck;
Nope. Because we can be in an intermediate state of registration, will be useful later.

2020-07-31 20:01 UTC, wishdasher commented on client/src/program/StudentProgramPage.tsx
> +        <GeneralStudentPage
Renamed to `StudentProgramPageRouter` (because that's its functionality) and `StudentProgramInfoPage`

2025-01-09 03:27 UTC, closed without merging